name: OreBreakPlugin
version: 1.0
api-version: 1.13
main: me.jakegore.orebreakplugin.OreBreakPlugin

commands:
  orebreak:
    description: Give the user a pickaxe
    usage: /<command>
    permission: <plugin name>.basic
    permission-message: You don't have <permission>